---
# roles/setup-nexus-repo/tasks/main.yml

- name: "Descargar el binario desde el Nexus Hosted"
  get_url:
    # Recuerda: Desde el contenedor usamos 'nexus-lab'
    url: "http://{{ nexus_user }}:{{ nexus_pass }}@nexus-lab:8081/repository/sonda-binary-store/network/net-tools.deb"
    dest: "/tmp/net-tools.deb"
    mode: '0644'

- name: "Instalar paquete .deb localmente"
  apt:
    deb: "/tmp/net-tools.deb"