---
# roles/setup-nexus-repo/tasks/main.yml

- name: "Backup del sources.list original"
  shell: "cp /etc/apt/sources.list /etc/apt/sources.list.bak"
  args:
    creates: /etc/apt/sources.list.bak

- name: "Inyectar configuración de Nexus"
  copy:
    dest: /etc/apt/sources.list
    content: |
      deb http://{{ nexus_user }}:{{ nexus_pass }}@{{ nexus_host }}:{{ nexus_port }}/repository/{{ nexus_repo }}/ jammy main restricted universe multiverse
      deb http://{{ nexus_user }}:{{ nexus_pass }}@{{ nexus_host }}:{{ nexus_port }}/repository/{{ nexus_repo }}/ jammy-updates main restricted universe multiverse
      deb http://{{ nexus_user }}:{{ nexus_pass }}@{{ nexus_host }}:{{ nexus_port }}/repository/{{ nexus_repo }}/ jammy-security main restricted universe multiverse
    mode: '0644'

- name: "Update manual para 'calentar' el Nexus"
  shell: "apt-get update"
  # Usamos shell porque no requiere python3-apt en el destino

- name: "Instalar python3-apt y herramientas (Ahora sí con apt)"
  shell: "apt-get install -y python3-apt net-tools curl"