---
- name: "Descargar el binario desde el Nexus Hosted"
  get_url:
    url: "http://{{ nexus_user }}:{{ nexus_pass }}@nexus-lab:8081/repository/raw-repo-lab/network/net-tools.deb./net-tools_1.60+git20181103.0eebece-1ubuntu5.4_amd64.deb"
    dest: "/tmp/net-tools.deb"
    mode: '0644'

- name: "Instalar mediante dpkg (Ignora repositorios y bloqueos)"
  command: "dpkg -i /tmp/net-tools.deb"
  # Usamos command en vez de apt para evitar que Ansible intente validar repositoriosg