---
- name: "Instalar herramientas de red"
  apt:
    name:
      - net-tools
      - curl
    state: present
    update_cache: yes

- name: "Crear estructura de directorios para la App"
  file:
    path: /opt/sonda_data/logs
    state: directory
    mode: '0755'
    owner: root

- name: "Personalizar el Banner de bienvenida"
  copy:
    dest: /etc/motd
    content: |
      ===============================================
      SERVIDOR DE LABORATORIO - SONDA DEVOPS
      Gestionado por: Ansible (Role: Prueba)
      Estado: Provisionado correctamente.
      ===============================================