---
- name: "Imprimir mensaje de depuracion en el motor"
  debug:
    msg: "Iniciando provisionamiento offline en el nodo..."

- name: "Crear un archivo de auditoria en el target"
  file:
    path: /tmp/auditoria_devops.txt
    state: touch
    mode: '0644'
    owner: root

- name: "Inyectar mensaje de bienvenida (MOTD)"
  copy:
    dest: /etc/motd
    content: |
      ===============================================
      SERVIDOR DE LABORATORIO - ENTORNO AISLADO
      Gestionado por: Ansible (Rol: Prueba)
      Estado: Provisionado sin salida a internet.
      ===============================================